language: perl
perl:
  - "5.22"
  - "5.20.1"

sudo: false

before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
  
install:
  - cpanm --quiet --notest --installdeps .

notifications:
  recipients:
    - xlat@cpan.org
  email:
    on_success: change
    on_failure: always